# this file containes the environment variables for the tests


# URLs

url_homepage:         https://jhakola.com/karhuhommat/index.html

# url_pd:
# url_aboutus:
# url_accountpage:
# url_loginpage:      /login_sign_up/index.html


